apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: spam-detector

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: registry.manty.co.kr/spam-detector
    newTag: latest
